replicaCount: 1

image:
  repository: lidarr
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8686

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""

extraObjects: []

