FROM digrouz/alpine-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG LIDARR_VERSION='2.6.4.4402'
ARG LIDARR_ARCH='x64'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    LIDARR_VERSION="${LIDARR_VERSION}" \
    LIDARR_ARCH="${LIDARR_ARCH}" \
    XDG_CONFIG_HOME='/config/xdg'
    
### Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      ca-certificates \
      curl \
    && \
    apk add --no-cache --virtual=run-deps \
      chromaprint \
      gcompat \
      icu \
      mediainfo \
      libintl \
      sqlite-libs \
    && \
    curl -SsL "https://github.com/lidarr/Lidarr/releases/download/v${LIDARR_VERSION}/Lidarr.master.${LIDARR_VERSION}.linux-musl-core-${LIDARR_ARCH}.tar.gz" -o /tmp/lidarr.tar.gz && \
    tar xzf /tmp/lidarr.tar.gz -C /opt && \
    echo "export XDG_CONFIG_HOME='${XDG_CONFIG_HOME}'" >> /etc/profile.d/docker-xdg.sh && \
    chmod 0755 /opt/Lidarr && \
    find /opt/Lidarr -type d -exec chmod 0755 {} \; && \
    find /opt/Lidarr -type f -exec chmod 0644 {} \; && \
    chmod 0755 \
      /opt/Lidarr/Lidarr \
      /opt/Lidarr/fpcalc \
     && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*
    
### Volume
Volume ["/config"]

### Expose ports
Expose 8686

