FROM alpine:3.16.0
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG LIDARR_VERSION='1.0.2.2592'
ARG LIDARR_ARCH='x64'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='lidarr' \
    APPUID='10032' \
    APPGID='10032' \
    LIDARR_VERSION="${LIDARR_VERSION}" \
    LIDARR_ARCH="${LIDARR_ARCH}" \
    XDG_CONFIG_HOME='/config/xdg'
    
### Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER="${APPUSER}" && \
    MYUID="${APPUID}" && \
    MYGID="${APPGID}" && \
    ConfigureUser && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      ca-certificates \
      curl \
    && \
    apk add --no-cache --virtual=run-deps \
      bash \
      ca-certificates \
      gcompat \
      icu \
      mediainfo \
      libintl \
      sqlite-libs \
      su-exec \
    && \
    apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/community --virtual=run-deps-testing \
      chromaprint \
    && \
    curl -SsL "https://github.com/lidarr/Lidarr/releases/download/v${LIDARR_VERSION}/Lidarr.master.${LIDARR_VERSION}.linux-musl-core-${LIDARR_ARCH}.tar.gz" -o /tmp/lidarr.tar.gz && \
    tar xzf /tmp/lidarr.tar.gz -C /opt && \
    echo "export XDG_CONFIG_HOME='${XDG_CONFIG_HOME}'" >> /etc/profile.d/docker-xdg.sh && \
    chmod 0755 /opt/Lidarr && \
    find /opt/Lidarr -type d -exec chmod 0755 {} \; && \
    find /opt/Lidarr -type f -exec chmod 0644 {} \; && \
    chmod 0755 /opt/Lidarr/Lidarr && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    mkdir /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*
    
### Volume
Volume ["/config","/downloads","/music"]

### Expose ports
Expose 8686

### Running User: not used, managed by docker-entrypoint.sh
#USER lidarr

### Start lidarr
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["lidarr-core"]
