apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-lidarr
  labels:
    app: {{ .Release.Name }}-lidarr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-lidarr
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-lidarr
    spec:
      containers:
        - name: lidarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8686
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-lidarr-config
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
