{{- if .Values.persistence.config.enabled }}
{{- if eq .Values.persistence.config.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: lidarr 
spec:
  accessModes:
    - {{ .Values.persistence.config.pvc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.pvc.size | quote }}
  {{- if .Values.persistence.config.pvc.storageClass }}
  storageClassName: {{ .Values.persistence.config.pvc.storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}
--- 
{{- if .Values.persistence.downloads.enabled }}
{{- if eq .Values.persistence.downloads.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-downloads-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: lidarr 
spec:
  accessModes:
    - {{ .Values.persistence.downloads.pvc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.pvc.size | quote }}
  {{- if .Values.persistence.downloads.pvc.storageClass }}
  storageClassName: {{ .Values.persistence.downloads.pvc.storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}   
---
{{- if .Values.persistence.music.enabled }}
{{- if eq .Values.persistence.music.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-music-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: lidarr 
spec:
  accessModes:
    - {{ .Values.persistence.music.pvc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.music.pvc.size | quote }}
  {{- if .Values.persistence.music.pvc.storageClass }}
  storageClassName: {{ .Values.persistence.music.pvc.storageClass | quote }}
  {{- end }}
{{- end }} 
{{- end }}

