---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-lidarr-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: lidarr
spec:
  ports:
  - port: 8686
    name: webui
    protocol: TCP
  selector:
    app.kubernetes.io/component: lidarr
